Repository RetroBat-Official/retrobat-setup, pull requests merged in 2024-10, with the labels that each got.

#183 es_padtokey
  system/templates/emulationstation/es_padtokey.cfg
Labels: enhancement

#184 Add savesstates and shortcuts to bizhawk
  system/templates/emulationstation/es_padtokey.cfg
Labels: enhancement

#186 n64 Controllers / translations / fix closing / remove m3u from 3do
  system/resources/inputmapping/n64Controllers.json
  system/templates/emulationstation/es_features.locale/fr/es-features.po
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/emulationstation/es_systems.cfg
Labels: bug, enhancement

#187 Add creation of system folder in saves\switch\ryujinx
  system/configgen/retrobat_tree.lst
Labels: enhancement

#188 BigPEmu - add gamecontrollersdb
  system/configgen/templates_files.lst
  system/templates/bigpemu/gamecontrollerdb.txt
Labels: enhancement

#190 Add lime3ds new executable to padtokey
  system/templates/emulationstation/es_padtokey.cfg
Labels: enhancement

#191 Translations
  system/templates/emulationstation/es_features.locale/fr/es-features.po
Labels: Traductions

#192 Fix build
  build.bat
  system/configgen/templates_files.lst
Labels: enhancement

#194 Flycast nvmem and exit ares
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/flycast/nvmem.zip
  system/templates/retroarch/saves/reicast/nvmem.naomi2.zip
  system/templates/retroarch/saves/reicast/nvmem_naomi.zip
Labels: bug, enhancement

#195 Translations
  system/templates/emulationstation/es_features.locale/fr/es-features.po
Labels: Traductions

#196 Add openjazz
  system/configgen/emulators_names.lst
  system/configgen/retrobat_tree.lst
  system/configgen/systems_names.lst
  system/configgen/templates_files.lst
  system/templates/emulationstation/es_features.locale/fr/es-features.po
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/emulationstation/es_systems.cfg
  system/templates/openjazz/openjazz.cfg
Labels: enhancement

#197 odyssey - videopac - add MAME
  system/resources/inputmapping/n64Controllers.json
  system/templates/emulationstation/es_systems.cfg
Labels: enhancement

#198 Update es-features.po
  system/templates/emulationstation/es_features.locale/fr/es-features.po
Labels: Traductions

#199 Add vg5k
  system/configgen/systems_names.lst
  system/templates/emulationstation/es_systems.cfg
  system/tools/controllerinfo.yml
Labels: enhancement
