Repository RetroBat-Official/retrobat-setup, pull requests merged in 2024-03, with the labels that each got.

#57 Ryujinx template
  system/configgen/retrobat_tree.lst
  system/templates/ryujinx/portable/Config.json
Labels: bug, enhancement

#58 Fix dolphin TRIFORCE es_menu
  .gitignore
  system/configgen/emulators_names.lst
  system/configgen/retrobat_tree.lst
  system/configgen/templates_files.lst
  system/es_menu/dolphin-triforce.menu
  system/es_menu/gamelist.xml
  system/es_menu/psxmame.menu
  system/resources/sdl2/SDL2_2.28.5.0_x64.dll
  system/resources/sdl2/SDL2_2.30.1.0_x64.dll
  system/templates/emulationstation/es_systems.cfg
  system/templates/psxmame/mame.ini
  system/templates/psxmame/nvram/nvram.zip
  system/tools/gamecontrollerdb.txt
Labels: bug

#60 Controllers multiple things
  build.bat
  system/resources/inputmapping/flycast_Arcade.yml
  system/resources/inputmapping/libretro_flycast_atomiswave.yml
  system/resources/inputmapping/libretro_flycast_naomi.yml
  system/resources/sdl2/SDL2_2.28.1.0_x64.dll
  system/resources/sdl2/SDL2_2.28.5.0_x64.dll
  system/resources/sdl2/SDL2_2.30.1.0_x64.dll
  system/templates/supermodel/ReShade.ini
  system/templates/supermodel/ReShadePreset.ini
  system/templates/supermodel/opengl32.dll
Labels: enhancement

#63 add gemrb entries
  system/configgen/retrobat_tree.lst
  system/configgen/systems_names.lst
  system/configgen/templates_files.lst
  system/templates/emulationstation/es_systems.cfg
Labels: enhancement

#64 Added fbneo standalone
  build.bat
  system/configgen/emulators_names.lst
  system/configgen/kill_process.lst
  system/configgen/retrobat_tree.lst
  system/configgen/templates_files.lst
  system/es_menu/fbneo.menu
  system/es_menu/gamelist.xml
  system/es_menu/media/fbneo-logo.png
  system/resources/inputmapping/fbneo.yml
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/emulationstation/es_systems.cfg
  system/templates/fbneo/config/fbneo64.ini
Labels: enhancement
