Repository RetroBat-Official/retrobat-setup, pull requests merged in 2025-07, with the labels that each got.

#342 Fix dolphin triforce and add teknoparrot
  system/templates/dolphin-triforce/GameSettings/GameSettings.zip
  system/templates/emulationstation/es_systems.cfg
  system/tools/teknoparrotInfo.yml
Labels: bug, Update

#344 Opengoal and launchers
  system/configgen/templates_files.lst
  system/templates/emulationstation/es_systems.cfg
  system/templates/opengoal/config/OpenGOAL/jak1/settings/display-settings.json
  system/templates/opengoal/config/OpenGOAL/jak1/settings/pc-settings.gc
  system/templates/opengoal/config/OpenGOAL/jak2/settings/display-settings.json
  system/templates/opengoal/config/OpenGOAL/jak2/settings/pc-settings.gc
Labels: enhancement, Update

#349 Ymir and m3U
  system/resources/inputmapping/saturnControllers.json
  system/templates/emulationstation/es_systems.cfg
  system/templates/ymir/Ymir.toml
Labels: enhancement, Update

#350 Update teknoparrot.yml
  system/resources/inputmapping/teknoparrot.yml
Labels: enhancement

#354 Update retroarch-core-options.cfg
  system/templates/retroarch/retroarch-core-options.cfg
Labels: Update

#357 Gopher config
  system/templates/gopher64/config.json
Labels: Update

#363 Update installer
  ICSharpCode.SharpZipLib.dll
  InstallerHost.exe
  InstallerHost.pdb
  RetroBuild.exe
  RetroBuild.pdb
  build.ini
Labels: enhancement

#369 Update builder
  InstallerHost.exe
  RetroBuild.exe
  build.ini
Labels: Update
