Repository RetroBat-Official/retrobat-setup, pull requests merged in 2025-06, with the labels that each got.

#320 Add ymir
  system/configgen/emulators_names.lst
  system/configgen/retrobat_tree.lst
  system/configgen/templates_files.lst
  system/es_menu/gamelist.xml
  system/es_menu/media/ymir-logo.png
  system/es_menu/ymir.menu
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/emulationstation/es_systems.cfg
  system/templates/ymir/Ymir.toml
Labels: Update

#323 Update discord link
  README.md
  system/configgen/templates_files.lst
  system/templates/play/config.xml
Labels: Update

#326 Update es_systems.cfg
  system/templates/emulationstation/es_systems.cfg
Labels: bug

#330 Turkish language translation
  system/templates/emulationstation/es_features.locale/tr/es-features.po
Labels: Traductions

#329 Update jgenesis-config.toml
  system/templates/jgenesis/jgenesis-config.toml
Labels: Update

#333 Add geargrafx core for supergrafx
  system/configgen/lrcores_names.lst
  system/templates/emulationstation/es_systems.cfg
  system/templates/retroarch/retroarch-core-options.cfg
Labels: Update

#337 Update es-features.po
  system/templates/emulationstation/es_features.locale/fr/es-features.po
Labels: bug, Traductions
