Repository RetroBat-Official/retrobat-setup, pull requests merged in 2025-01, with the labels that each got.

#236 Pdark and Kronos
  system/configgen/emulators_names.lst
  system/configgen/retrobat_tree.lst
  system/configgen/systems_names.lst
  system/configgen/templates_files.lst
  system/templates/emulationstation/es_systems.cfg
  system/templates/kronos/kronos.ini
  system/templates/pdark/pd.ini
  system/templates/xemu/xemu.ini
Labels: Feature request, Update

#237 Add starship
  system/configgen/emulators_names.lst
  system/configgen/systems_names.lst
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/emulationstation/es_systems.cfg
Labels: Feature request

#238 Add ps4 and snes9x shortcuts
  system/configgen/emulators_names.lst
  system/configgen/retrobat_tree.lst
  system/configgen/systems_names.lst
  system/configgen/templates_files.lst
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/emulationstation/es_systems.cfg
  system/templates/shadps4/user/config.toml
Labels: Feature request, Update

#239 Multiple controller fixes (mednafen / teknoparrot)
  system/configgen/templates_files.lst
  system/resources/inputmapping/teknoparrot.yml
  system/templates/emulationstation/es_features.locale/fr/es-features.po
  system/templates/lime3ds/user/config/qt-config.ini
  system/tools/controllerinfo.yml
Labels: bug, enhancement

#242 teknoparrot explanation
  system/tools/controllerinfo.yml
Labels: enhancement

#243 Wheels and TP reshade
  system/configgen/retrobat_tree.lst
  system/configgen/templates_files.lst
  system/resources/inputmapping/wheels/flycast_wheels.yml
  system/resources/inputmapping/wheels/model3_wheels.yml
  system/resources/inputmapping/wheels/pcsx2_wheels.yml
  system/shaders/configs/sindenborder/rendering-defaults.yml
  system/tools/gamecontrollerdb.txt
  system/tools/teknoparrotReshade.yml
Labels: enhancement

#244 Teknoparrot stuff
  build.bat
  system/resources/inputmapping/teknoparrot.yml
  system/resources/inputmapping/wheels/model2_wheels.yml
  system/shaders/configs/curvature/rendering-defaults.yml
  system/shaders/configs/enhanced/rendering-defaults.yml
  system/shaders/configs/ntsc/rendering-defaults.yml
  system/shaders/configs/scanlines/rendering-defaults.yml
  system/shaders/configs/zfast/rendering-defaults.yml
  system/tools/gamecontrollerdb.txt
  system/tools/teknoparrotReshade.yml
Labels: enhancement

#247 Add project64 padtokey for savestates
  system/templates/emulationstation/es_padtokey.cfg
Labels: enhancement

#248 Fix reshade executable for aliensextermination
  system/tools/teknoparrotReshade.yml
Labels: enhancement

#249 M2emulator templates + teknoparrot executable file
  system/configgen/retrobat_tree.lst
  system/configgen/templates_files.lst
  system/templates/m2emulator/crosshairs.zip
  system/templates/m2emulator/scripts.zip
  system/tools/teknoparrotExecutables.yml
Labels: enhancement

#251 Traductions et mappings teknoparrot
  system/resources/inputmapping/teknoparrot.yml
  system/templates/emulationstation/es_features.locale/fr/es-features.po
Labels: enhancement, Traductions

#252 Add trad feature Demul / mamehook
  system/resources/inputmapping/teknoparrot.yml
  system/templates/emulationstation/es_features.locale/cs_CZ/es-features.po
  system/templates/emulationstation/es_features.locale/en_GB/es-features.po
  system/templates/emulationstation/es_features.locale/es-features-template.po
  system/templates/emulationstation/es_features.locale/es/es-features.po
  system/templates/emulationstation/es_features.locale/fr/es-features.po
  system/templates/emulationstation/es_features.locale/it/es-features.po
  system/templates/emulationstation/es_features.locale/ja_JP/es-features.po
  system/templates/emulationstation/es_features.locale/nl/es-features.po
  system/templates/emulationstation/es_features.locale/pl/es-features.po
  system/templates/emulationstation/es_features.locale/pt_BR/es-features.po
  system/templates/emulationstation/es_features.locale/ru_RU/es-features.po
Labels: enhancement, Traductions

#255 Add emulator
  system/tools/controllerinfo.yml
Labels: enhancement

#256 Fix duplicates in yml
  system/resources/inputmapping/fbneo.yml
  system/resources/inputmapping/libretro_flycast_naomi.yml
Labels: bug

#257 Add doukutsu_rs
  build.bat
  system/templates/emulationstation/es_systems.cfg
Labels: enhancement
