Repository RetroBat-Official/retrobat-setup, pull requests merged in 2025-03, with the labels that each got.

#271 altirra, citron
  system/configgen/emulators_names.lst
  system/configgen/retrobat_tree.lst
  system/configgen/templates_files.lst
  system/es_menu/altirra.menu
  system/es_menu/gamelist.xml
  system/es_menu/media/altirra-logo.png
  system/padtokey/daphne.daphne.keys.old
  system/padtokey/daphne.hypseus.keys
  system/templates/altirra/Altirra.ini
  system/templates/altirra/Configure altirra.bat
  system/templates/citron/qt-config.ini
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/emulationstation/es_systems.cfg
  system/tools/controllerinfo.yml
Labels: enhancement

#276 Add gopher64
  system/configgen/emulators_names.lst
  system/configgen/retrobat_tree.lst
  system/configgen/templates_files.lst
  system/es_menu/gamelist.xml
  system/es_menu/gopher64.menu
  system/es_menu/media/gopher64-logo.png
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/emulationstation/es_systems.cfg
  system/templates/gopher64/config.json
Labels: Update

#278 Translations
  system/templates/emulationstation/es_features.locale/fr/es-features.po
Labels: Traductions

#279 Update teknoparrotReshade.yml
  system/tools/teknoparrotReshade.yml
Labels: enhancement

#280 MelonDS
  system/configgen/templates_files.lst
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/melonds/melonDS.ini
Labels: Update

#281 Update teknoparrot.yml
  system/resources/inputmapping/teknoparrot.yml
Labels: enhancement

#283 Add azahar
  system/configgen/emulators_names.lst
  system/configgen/retrobat_tree.lst
  system/configgen/templates_files.lst
  system/es_menu/azahar.menu
  system/es_menu/gamelist.xml
  system/es_menu/media/azahar-logo.png
  system/templates/azahar/portable.txt
  system/templates/azahar/user/config/qt-config.ini
  system/templates/emulationstation/es_padtokey.cfg
  system/templates/emulationstation/es_systems.cfg
  system/tools/controllerinfo.yml
Labels: Update

#284 Bump duckstation and pcsx2
  system/configgen/templates_files.lst
  system/templates/duckstation/settings.ini
  system/templates/pcsx2/inis/PCSX2.ini
  system/tools/SDL3.dll
Labels: Update

#285 Teknoparrot : rename teknoparrotExecutables file
  system/tools/teknoparrotExecutables.yml
  system/tools/teknoparrotInfo.yml
Labels: enhancement

#286 RPCS3 config file
  system/templates/rpcs3/config.yml
  system/templates/shadps4/user/config.toml
Labels: Update

#287 Fix xbox series X in cemu
  system/tools/controllerinfo.yml
Labels: bug
