Repository RetroBat-Official/retrobat-setup, pull requests merged in 2025-02, with the labels that each got.

#260 Add missing aquarius folder and m3u for ps4
  system/configgen/systems_names.lst
  system/es_menu/gamelist.xml
  system/es_menu/lime3ds.menu
  system/es_menu/media/shadps4-logo.png
  system/es_menu/shadps4.menu
  system/templates/emulationstation/es_systems.cfg
  system/templates/m2emulator/scripts.zip
Labels: bug, enhancement

#261 Update es-features.po
  system/templates/emulationstation/es_features.locale/fr/es-features.po
Labels: bug, Traductions

#265 Add singe system
  system/configgen/systems_names.lst
  system/templates/emulationstation/es_systems.cfg
Labels: enhancement
